chore: add terraform-google-gen-ai-document-summarization repo
GoogleCloudPlatform/cloud-foundation-toolkit pull request #1680
Opened 2023-06-22 18:19 UTC by yil532

Onboarding https://github.com/GoogleCloudPlatform/terraform-google-gen-ai-document-summarization. This repo hosts UP16.1.

2023-06-22 18:25 UTC, nicain reviewed
LGTM

2023-06-29 23:21 UTC, bharathkkb approved these changes

2023-06-29 23:38 UTC, bharathkkb requested changes
Thanks for the PR @yil532. Looks like @g-awmalik had some additional comments in b/289379695#comment2 around repo naming which would be good to resolve before we apply this.

2023-06-29 23:45 UTC, bharathkkb commented on infra/terraform/test-org/org/locals.tf
> +      owners          = ["asrivast", "balajismaniam", "erschmid", "liyvonne", "nicain"]
Please use github usernames

```suggestion
      owners          = ["asrivas", "balajismaniam", "telpirion", "yil532", "nicain"]
```

2023-06-29 23:55 UTC, apeabody commented
@bharathkkb - For lint: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1693

2023-06-30 17:19 UTC, balajismaniam commented
The repo has been renamed to https://github.com/GoogleCloudPlatform/terraform-genai-doc-summarization. CC: @bharathkkb

2023-06-30 17:38 UTC, bharathkkb commented
Thanks @balajismaniam

2023-06-30 17:44 UTC, bharathkkb approved these changes

2023-06-30 17:44 UTC, bharathkkb commented on infra/terraform/test-org/org/locals.tf
> +      name            = "terraform-google-gen-ai-document-summarization"
```suggestion
      name            = "terraform-genai-doc-summarization"
```

2023-06-30 17:44 UTC, bharathkkb commented on infra/terraform/test-org/ci-triggers/locals.tf
> +    "gen-ai-document-summarization" = "terraform-google-gen-ai-document-summarization"
```suggestion
    "gen-ai-document-summarization" = "terraform-genai-doc-summarization"
```

2023-06-30 17:57 UTC, bharathkkb commented on infra/terraform/test-org/org/locals.tf
> +      short_name      = "gen-ai-document-summarization"
```suggestion
      short_name      = "genai-doc-summarization"
```

2023-06-30 17:57 UTC, bharathkkb commented on infra/terraform/test-org/ci-triggers/locals.tf
> +    "gen-ai-document-summarization" = "terraform-genai-doc-summarization"
```suggestion
    "genai-doc-summarization" = "terraform-genai-doc-summarization"
```

2023-06-30 18:13 UTC, bharathkkb commented
This had been applied

2023-06-30 18:14 UTC, merged