chore: don't run stale bot on forks
GoogleCloudPlatform/cloud-foundation-toolkit pull request #1783
Opened 2023-08-21 09:22 UTC by lauraseidler

Forks generally don't have open issues - this PR turns off the stale bot for them, to avoid useless action runs + the notifications arising from them.

Docs: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

2023-08-21 17:43 UTC, apeabody requested changes
Thanks for the contribution @lauraseidler!  Linter found an extra space.

2023-08-21 17:43 UTC, apeabody commented on infra/terraform/test-org/github/resources/stale.yml
> +    if: github.repository_owner == 'GoogleCloudPlatform' || github.repository_owner == 'terraform-google-modules'
For the LINT CI

```suggestion
    if: github.repository_owner == 'GoogleCloudPlatform' || github.repository_owner == 'terraform-google-modules'
```

2023-08-22 17:17 UTC, apeabody commented
applied

2023-08-22 17:17 UTC, merged

2023-08-23 10:07 UTC, lauraseidler commented
Thank you!