feat: update owners for backup-dr
GoogleCloudPlatform/cloud-foundation-toolkit pull request #2513
Opened 2024-08-13 16:45 UTC by ankushpareddy

Adding myself and niharika as owners for backupDR terraform

2024-08-14 15:51 UTC, g-awmalik approved these changes

2024-08-14 16:13 UTC, g-awmalik commented
@ankushpareddy - please sure owners are valid Github usernames.

2024-08-14 16:13 UTC, g-awmalik commented on infra/terraform/test-org/org/locals.tf
> +      owners      = ["umeshkumhar", "ankushpa", "nkuravi"]
"ankushpa" & "nkuravi" are not valid usernames

2024-08-14 16:14 UTC, g-awmalik requested changes
Replace ldaps with Github usernames.

2024-09-14 03:05 UTC, bharathkkb commented
Please join GoogleCloudPlatform github org for `ankushpareddy`

2024-11-21 23:02 UTC, closed without merging